<html>
	<?php include REG_PATH.'/head.inc';?>
	<body>
		<div class="container">
			<div class="row">
				<div class="pen-title">
					<h1>タイトル</h1>
				</div>
				<div class="container">
					<div class="card"></div>
					<div class="card">
						<h1 class="title">登録完了しました。</h1>
						<div class="button-container">
							<button type='button' onclick="location.href='<?php echo WEB_ROOT_PATH?>/login.php'"><span>ログイン画面へ</span></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>