<html>
	<?php include THREAD_PATH.'/head2.inc';?>
	<body>
		<?php include COMMENT_PATH.'/navi.inc';?>
		<div class="container" style="padding-left: 17%;">
			<div class="row profile">
				<div class="profile-sidebar" style="width: 505px; height:35%;">
					<h1 style='text-align:center;'>削除完了</h1>
					<button type='button' onclick="location.href='<?php echo WEB_ROOT_PATH?>/userThread.php'" class='center-block btn-default btn-lg'>スレッド一覧</button>
					<button type='button' onclick="location.href='<?php echo WEB_ROOT_PATH?>/top.php'" class='center-block btn-default btn-lg'>TOP</button>
				</div>
			</div>
		</div>
	</body>
</html>