<html>
	<head>
		<?php include USER_PATH.'/bootstrap.inc';?>
		<link rel="stylesheet" type="text/css" href="css/top1.css" media="all">
		<link rel="stylesheet" type="text/css" href="css/pagging.css" media="all">
		<style type="text/css">
			a:link { color:#000000; text-decoration:none }
			a:visited { color:#000000; text-decoration:none }
			a:hover { color:#000000; text-decoration:none }
			a:active { color:#000000; text-decoration:none }
		</style>
	</head>
	<body>
		<?php include USER_PATH.'/navi.inc';?>
		<img src='<?php echo NAI ?>' style='display:block;margin:auto;width:30%;'>
	</body>
</html>